# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisions',
            name='photo',
            field=models.ImageField(default='demo.png', upload_to=''),
            preserve_default=False,
        ),
    ]
